UPDATE gbua_cgdb.BookingFood SET Name = '41', address = '', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 1;
UPDATE gbua_cgdb.BookingFood SET Name = 'жопная 2', address = '', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 2;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'жопная 2', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 3;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 4;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 5;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 6;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярик', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 7;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 8;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 9;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 10;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 11;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 12;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 13;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 14;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 15;
UPDATE gbua_cgdb.BookingFood SET Name = 'бббб', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 16;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = 'Шотаруставелли 24', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 17;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 18;
UPDATE gbua_cgdb.BookingFood SET Name = 'ввв', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 19;
UPDATE gbua_cgdb.BookingFood SET Name = 'f', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 20;
UPDATE gbua_cgdb.BookingFood SET Name = 'Ярослав', address = '41', email = 'yaroslavkondratenko54@gmail.com', phone = '0934105627', foodname = null WHERE ID = 21;
