UPDATE gbua_cgdb.CarsClassData SET Name = 'Эконом' WHERE CarsClassID = 1 AND LangID = 1;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Econom' WHERE CarsClassID = 1 AND LangID = 2;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Эконом' WHERE CarsClassID = 1 AND LangID = 3;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Економ' WHERE CarsClassID = 1 AND LangID = 4;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Стандарт' WHERE CarsClassID = 2 AND LangID = 1;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Standart' WHERE CarsClassID = 2 AND LangID = 2;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Стандарт' WHERE CarsClassID = 2 AND LangID = 3;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Стандарт' WHERE CarsClassID = 2 AND LangID = 4;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Бизнес' WHERE CarsClassID = 3 AND LangID = 1;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Business' WHERE CarsClassID = 3 AND LangID = 2;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Бизнес' WHERE CarsClassID = 3 AND LangID = 3;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Бізнес' WHERE CarsClassID = 3 AND LangID = 4;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Внедорожник' WHERE CarsClassID = 4 AND LangID = 1;
UPDATE gbua_cgdb.CarsClassData SET Name = 'SUV' WHERE CarsClassID = 4 AND LangID = 2;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Внедорожник' WHERE CarsClassID = 4 AND LangID = 3;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Позашляховик' WHERE CarsClassID = 4 AND LangID = 4;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Минивен' WHERE CarsClassID = 5 AND LangID = 1;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Minivan' WHERE CarsClassID = 5 AND LangID = 2;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Минивен' WHERE CarsClassID = 5 AND LangID = 3;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Мінівен' WHERE CarsClassID = 5 AND LangID = 4;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Спорт купе' WHERE CarsClassID = 6 AND LangID = 1;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Sportcar' WHERE CarsClassID = 6 AND LangID = 2;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Спорт купе' WHERE CarsClassID = 6 AND LangID = 3;
UPDATE gbua_cgdb.CarsClassData SET Name = 'Спорт купе' WHERE CarsClassID = 6 AND LangID = 4;
