create table Cars
(
    CarsID                int                                  not null
        primary key,
    name                  varchar(50) collate utf8_general_ci  null,
    `1day`                int                                  null,
    `3days`               int                                  null,
    `8days`               int                                  null,
    `31days`              int                                  null,
    DriverPrice           int                                  null,
    description           varchar(255) collate utf8_general_ci null,
    options               varchar(255) collate utf8_general_ci null,
    booked                tinyint(1)                           null,
    image                 varchar(255) collate utf8_general_ci null,
    CarsCity              int                                  null,
    CarsKpp               int                                  null,
    CarsTypeKuzov         int                                  null,
    CarsPrivod            int                                  null,
    Owner                 int                                  null,
    CountPersons          int                                  null,
    EngineVolume          decimal(10, 1)                       null,
    CarsPetrolID          int                                  null,
    CarsClass             int                                  null,
    image1                varchar(255)                         null,
    image2                varchar(255)                         null,
    image3                varchar(255)                         null,
    image4                varchar(255)                         null,
    transfer              varchar(255)                         null,
    transferpricebycar    int                                  null,
    transferpricebyperson int                                  null,
    constraint FK_Cars_CarsCity
        foreign key (CarsCity) references CarsCity (CarsCityID)
)
    collate = cp1251_general_ci
    avg_row_length = 963;

INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (1, 'FORD Escape (2012)', 54, 50, 46, 43, 50, null, null, 1, '/images/cars/Ford-Escape-Hybrid-2009.jpg.510x400_q85_crop-crop.jpg', 1, 1, 1, 1, 12, 5, 2.5, 0, 0, '/images/cars/viber_image_2022-05-11_16-03-19-091.jpg', '/images/cars/viber_image_2022-05-11_16-03-19-986.jpg', '/images/cars/viber_image_2022-05-11_16-03-21-068.jpg', null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (2, 'FORD Escape (2010)', 54, 50, 46, 43, 50, null, null, 1, '/images/cars/Cars_500_300_1_2.png', 1, 1, 4, 2, 12, 5, 2.3, 0, 0, '/images/cars/viber_image_2022-05-11_16-03-37-524.jpg', '/images/cars/viber_image_2022-05-11_16-03-38-176.jpg', '/images/cars/viber_image_2022-05-11_16-03-33-270.jpg', null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (3, 'Mazda 5 Minivan (2013)', 46, 45, 38, 36, 50, null, null, 1, '/images/cars/Cars_500_300_3.png', 1, 1, 4, 3, 12, 6, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (4, 'HONDA INSIGHT (2009)', 59, 54, 48, 45, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 5, 2, 12, 5, 1.3, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (5, 'TOYOTA PRIUS (2008)', 0, 0, 0, 0, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 1.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (6, 'TOYOTA PRIUS (2009)', 0, 0, 0, 0, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 1.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (7, 'Mazda 6 (2015) blue', 54, 50, 46, 43, 50, null, null, 1, '/images/cars/Cars_500_300_7.png', 1, 1, 3, 1, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (8, 'Mazda 6 (2015) black', 54, 50, 46, 43, 50, null, null, 1, '/images/cars/Cars_500_300_7.png', 1, 1, 3, 1, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (9, 'Mazda 6 (2015) grey', 54, 50, 46, 43, 50, null, null, 1, '/images/cars/Cars_500_300_7.png', 1, 1, 3, 1, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (10, 'Mazda 3 - 2015', 46, 45, 38, 36, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 2.0, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (11, 'Mazda 3 hatchback (2015)', 46, 45, 38, 36, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 2.0, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (12, 'Mazda 3 sedan (2015)', 46, 45, 38, 36, 50, '', null, 1, '/images/cars/Cars_500_300_12.png', 1, 1, 3, 1, 12, 5, 2.0, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (13, 'Mazda 3 (2016)', 46, 45, 38, 36, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 2.0, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (14, 'Mazda CX-5 (2015)', 63, 58, 52, 47, 50, null, null, 1, '/images/cars/Cars_500_300_14.png', 1, 1, 3, 3, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (15, 'Jeep compas (2016)', 69, 65, 60, 56, 50, null, null, 1, '/images/cars/Cars_500_300_15.png', 1, 1, 3, 3, 12, 5, 2.4, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (16, 'SUBARU forester (2015)', 58, 53, 49, 45, 50, null, null, 1, '/images/cars/Cars_500_300_16.png', 1, 1, 3, 3, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (17, 'Jeep Renegade trailhawk (2016)', 69, 65, 60, 56, 50, null, null, 1, '/images/cars/Cars_500_300_17.png', 1, 1, 3, 3, 12, 5, 2.4, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (18, 'Honda CRV (2012)', 59, 54, 48, 45, 50, null, null, 1, '/images/cars/Cars_500_300_18.png', 1, 1, 3, 3, 12, 5, 2.4, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (19, 'Volkswagen jetta (2016)', 0, 0, 0, 0, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (20, 'Toyota rav 4 (2018)', 0, 0, 0, 0, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 3, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (21, 'Chevrolet volt (2013)', 0, 0, 0, 0, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 1, 12, 5, 1.4, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (22, 'Hyndai ix35 (2016)', 0, 0, 0, 0, 50, null, null, 1, '/images/cars/prius.jpeg', 1, 1, 3, 3, 12, 5, 2.5, 0, 0, null, null, null, null, null, null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (23, 'Mercedes VITO', null, null, null, null, null, null, null, 1, '/images/mercedes-vito-rentalauto-car-rental-georgia-oam3ip7v4ur79wp2zpfkym604psg0b5772klbj01ic.jpg', 1, 1, 1, 1, 1, 7, 2.0, 0, 0, 'mercedes-vito-rentalauto-car-rental-georgia-oam3ip7v4ur79wp2zpfkym604psg0b5772klbj01ic.jpg', null, null, null, '1', null, null);
INSERT INTO gbua_cgdb.Cars (CarsID, name, `1day`, `3days`, `8days`, `31days`, DriverPrice, description, options, booked, image, CarsCity, CarsKpp, CarsTypeKuzov, CarsPrivod, Owner, CountPersons, EngineVolume, CarsPetrolID, CarsClass, image1, image2, image3, image4, transfer, transferpricebycar, transferpricebyperson) VALUES (24, 'Mercedes R350', null, null, null, null, null, null, null, null, '/images/2010-Mercedes-Benz-R-Class-FrontSide_MSR101_505x375.jpg', 1, 1, 1, 1, 12, 5, 3.5, 0, 0, 'mercedes-vito-rentalauto-car-rental-georgia-oam3ip7v4ur79wp2zpfkym604psg0b5772klbj01ic.jpg', null, null, null, '1', null, null);
