UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Выходные в Кахетии', LinkSrc = '/page/tour-kaheti-3days.html' WHERE LinkId = 1 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Weekends in Kakheti', LinkSrc = '/en/page/tour-kaheti-3days.html' WHERE LinkId = 1 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Выходные в Кахетии', LinkSrc = '/he/page/tour-kaheti-3days.html' WHERE LinkId = 1 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Вихідні в Кахетії', LinkSrc = '/ua/page/tour-kaheti-3days.html' WHERE LinkId = 1 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Выходные в Казбек', LinkSrc = '/page/tour-kazbeg-3-days.html' WHERE LinkId = 2 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Weekends in Kazbegi', LinkSrc = '/en/page/tour-kazbeg-3-days.html' WHERE LinkId = 2 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Выходные в Казбек', LinkSrc = '/he/page/tour-kazbeg-3-days.html' WHERE LinkId = 2 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Вихідні в Казбегі', LinkSrc = '/ua/page/tour-kazbeg-3-days.html' WHERE LinkId = 2 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Боржоми-Ахалцихе-Вардзия', LinkSrc = '/page/tour-borjomi-vardzia-4-days.html' WHERE LinkId = 3 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Borjomi-Akhaltsikhe-Vardzia', LinkSrc = '/en/page/tour-borjomi-vardzia-4-days.html' WHERE LinkId = 3 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Боржоми-Ахалцихе-Вардзия', LinkSrc = '/he/page/tour-borjomi-vardzia-4-days.html' WHERE LinkId = 3 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Боржомі-Ахалцихе-Вардзія', LinkSrc = '/ua/page/tour-borjomi-vardzia-4-days.html' WHERE LinkId = 3 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбилиси и его окрестности', LinkSrc = '/page/tour-around-tbilisi-5-days.html' WHERE LinkId = 4 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Tbilisi and its surroundings', LinkSrc = '/en/page/tour-around-tbilisi-5-days.html' WHERE LinkId = 4 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбилиси и его окрестности', LinkSrc = '/he/page/tour-around-tbilisi-5-days.html' WHERE LinkId = 4 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбілісі і його околиці', LinkSrc = '/ua/page/tour-around-tbilisi-5-days.html' WHERE LinkId = 4 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбилиси и поездка в Кахетиею', LinkSrc = '/page/tour-around-tbilisi-kaheti-5-days.html' WHERE LinkId = 5 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Tbilisi and a trip to Kakheti', LinkSrc = '/en/page/tour-around-tbilisi-kaheti-5-days.html' WHERE LinkId = 5 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбилиси и поездка в Кахетиею', LinkSrc = '/he/page/tour-around-tbilisi-kaheti-5-days.html' WHERE LinkId = 5 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбілісі та поїздка до Кахетії', LinkSrc = '/ua/page/tour-around-tbilisi-kaheti-5-days.html' WHERE LinkId = 5 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'В горы и на море', LinkSrc = '/page/tour-tbilisi-batumi-5-days.html' WHERE LinkId = 6 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'To the mountains and to the sea', LinkSrc = '/en/page/tour-tbilisi-batumi-5-days.html' WHERE LinkId = 6 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'В горы и на море', LinkSrc = '/he/page/tour-tbilisi-batumi-5-days.html' WHERE LinkId = 6 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'В гори та на море', LinkSrc = '/ua/page/tour-tbilisi-batumi-5-days.html' WHERE LinkId = 6 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Зима в Гудаури', LinkSrc = '/page/tour-to-gudauri-5-days.html' WHERE LinkId = 7 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Winter in Gudauri', LinkSrc = '/en/page/tour-to-gudauri-5-days.html' WHERE LinkId = 7 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Зима в Гудаури', LinkSrc = '/he/page/tour-to-gudauri-5-days.html' WHERE LinkId = 7 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Зима в Гудаурі', LinkSrc = '/ua/page/tour-to-gudauri-5-days.html' WHERE LinkId = 7 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Зима в Бакуриани', LinkSrc = '/page/tour-to-bakuriani-5-days.html' WHERE LinkId = 8 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Winter in Bakuriani', LinkSrc = '/en/page/tour-to-bakuriani-5-days.html' WHERE LinkId = 8 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Зима в Бакуриани', LinkSrc = '/he/page/tour-to-bakuriani-5-days.html' WHERE LinkId = 8 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Зима в Бакуріані', LinkSrc = '/ua/page/tour-to-bakuriani-5-days.html' WHERE LinkId = 8 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кулинарный тур', LinkSrc = '/page/tour-culinary-around-georgia-7-days.html' WHERE LinkId = 9 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Culinary tour', LinkSrc = '/en/page/tour-culinary-around-georgia-7-days.html' WHERE LinkId = 9 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кулинарный тур', LinkSrc = '/he/page/tour-culinary-around-georgia-7-days.html' WHERE LinkId = 9 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кулінарний тур', LinkSrc = '/ua/page/tour-culinary-around-georgia-7-days.html' WHERE LinkId = 9 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'От Тбилиси до Батуми', LinkSrc = '/page/tour-tbilisi-batumi-7-days.html' WHERE LinkId = 10 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'From Tbilisi to Batumi', LinkSrc = '/en/page/tour-tbilisi-batumi-7-days.html' WHERE LinkId = 10 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'От Тбилиси до Батуми', LinkSrc = '/he/page/tour-tbilisi-batumi-7-days.html' WHERE LinkId = 10 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Від Тбілісі до Батумі', LinkSrc = '/ua/page/tour-tbilisi-batumi-7-days.html' WHERE LinkId = 10 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Узнай Грузию за 8 дней', LinkSrc = '/page/tour-around-georgia-8-days.html' WHERE LinkId = 11 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Learn Georgia in 8 days', LinkSrc = '/en/page/tour-around-georgia-8-days.html' WHERE LinkId = 11 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Узнай Грузию за 8 дней', LinkSrc = '/he/page/tour-around-georgia-8-days.html' WHERE LinkId = 11 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Пізнай Грузію за 8 днів', LinkSrc = '/ua/page/tour-around-georgia-8-days.html' WHERE LinkId = 11 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Грузия и Армения', LinkSrc = '/page/tour-to-armenia-6-days.html' WHERE LinkId = 12 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Georgia and Armenia', LinkSrc = '/en/page/tour-to-armenia-6-days.html' WHERE LinkId = 12 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Грузия и Армения', LinkSrc = '/he/page/tour-to-armenia-6-days.html' WHERE LinkId = 12 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Грузія та Вірменія', LinkSrc = '/ua/page/tour-to-armenia-6-days.html' WHERE LinkId = 12 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбилиси', LinkSrc = '/page/excursion-in-tbilisi.html' WHERE LinkId = 13 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Tbilisi', LinkSrc = '/en/page/excursion-in-tbilisi.html' WHERE LinkId = 13 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбилиси', LinkSrc = '/he/page/excursion-in-tbilisi.html' WHERE LinkId = 13 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Тбілісі', LinkSrc = '/ua/page/excursion-in-tbilisi.html' WHERE LinkId = 13 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Мцхета и древние монастыри', LinkSrc = '/page/excursion-to-mtskheta.html' WHERE LinkId = 14 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Mtskheta and ancient monasteries', LinkSrc = '/en/page/excursion-to-mtskheta.html' WHERE LinkId = 14 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Мцхета и древние монастыри', LinkSrc = '/he/page/excursion-to-mtskheta.html' WHERE LinkId = 14 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Мцхета і стародавні монастирі', LinkSrc = '/ua/page/excursion-to-mtskheta.html' WHERE LinkId = 14 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Казбек (Степанцминда)', LinkSrc = '/page/excursion-in-kazbeg.html' WHERE LinkId = 15 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Kazbegi (Stepantsminda)', LinkSrc = '/en/page/excursion-in-kazbeg.html' WHERE LinkId = 15 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Казбек (Степанцминда)', LinkSrc = '/he/page/excursion-in-kazbeg.html' WHERE LinkId = 15 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Казбегі (Степанцмінда)', LinkSrc = '/ua/page/excursion-in-kazbeg.html' WHERE LinkId = 15 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Мцхета - Уплисцихе - Гори', LinkSrc = '/page/excursion-to-mtskheta-upliscihe-gori.html' WHERE LinkId = 16 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Mtskheta - Uplistsikhe - Gori', LinkSrc = '/en/page/excursion-to-mtskheta-upliscihe-gori.html' WHERE LinkId = 16 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Мцхета - Уплисцихе - Гори', LinkSrc = '/he/page/excursion-to-mtskheta-upliscihe-gori.html' WHERE LinkId = 16 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Мцхета - Уплисцихе - Горі', LinkSrc = '/ua/page/excursion-to-mtskheta-upliscihe-gori.html' WHERE LinkId = 16 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Гудаури', LinkSrc = '/page/excursion-to-gudauri.html' WHERE LinkId = 17 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Gudauri', LinkSrc = '/en/page/excursion-to-gudauri.html' WHERE LinkId = 17 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Гудаури', LinkSrc = '/he/page/excursion-to-gudauri.html' WHERE LinkId = 17 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Гудаурі', LinkSrc = '/ua/page/excursion-to-gudauri.html' WHERE LinkId = 17 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Бакуриани', LinkSrc = '/page/excursion-to-bakuriani.html' WHERE LinkId = 18 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Bakuriani', LinkSrc = '/en/page/excursion-to-bakuriani.html' WHERE LinkId = 18 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Бакуриани', LinkSrc = '/he/page/excursion-to-bakuriani.html' WHERE LinkId = 18 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Бакуріані', LinkSrc = '/ua/page/excursion-to-bakuriani.html' WHERE LinkId = 18 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кахетия. Винный завод Шуми', LinkSrc = '/page/excursion-to-kaheti-winery-shumi.html' WHERE LinkId = 19 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Kakheti. Shumi Winery', LinkSrc = '/en/page/excursion-to-kaheti-winery-shumi.html' WHERE LinkId = 19 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кахетия. Винный завод Шуми', LinkSrc = '/he/page/excursion-to-kaheti-winery-shumi.html' WHERE LinkId = 19 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кахеті. Винний завод Шумі', LinkSrc = '/ua/page/excursion-to-kaheti-winery-shumi.html' WHERE LinkId = 19 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Боржоми-Ахалцихе-Вардзия', LinkSrc = '/page/excursion-to-borjomi-vardzia.html' WHERE LinkId = 20 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Borjomi-Akhaltsikhe-Vardzia', LinkSrc = '/en/page/excursion-to-borjomi-vardzia.html' WHERE LinkId = 20 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Боржоми-Ахалцихе-Вардзия', LinkSrc = '/he/page/excursion-to-borjomi-vardzia.html' WHERE LinkId = 20 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Боржомі-Ахалціхе-Вардзія', LinkSrc = '/ua/page/excursion-to-borjomi-vardzia.html' WHERE LinkId = 20 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Дманиси. Первые европейцы', LinkSrc = '/page/excursion-to-dmanisi-first-europeans.html' WHERE LinkId = 21 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Dmanisi. The first Europeans', LinkSrc = '/en/page/excursion-to-dmanisi-first-europeans.html' WHERE LinkId = 21 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Дманиси. Первые европейцы', LinkSrc = '/he/page/excursion-to-dmanisi-first-europeans.html' WHERE LinkId = 21 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Дманісі. перші Європейці', LinkSrc = '/ua/page/excursion-to-dmanisi-first-europeans.html' WHERE LinkId = 21 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Монастырь Давид-Гареджа', LinkSrc = '/page/excursion-to-monastery-david-gareja.html' WHERE LinkId = 22 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'The Monastery of David-Gareja', LinkSrc = '/en/page/excursion-to-monastery-david-gareja.html' WHERE LinkId = 22 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Монастырь Давид-Гареджа', LinkSrc = '/he/page/excursion-to-monastery-david-gareja.html' WHERE LinkId = 22 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Монастир Давид-Гареджі', LinkSrc = '/ua/page/excursion-to-monastery-david-gareja.html' WHERE LinkId = 22 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кахетия. Винный завод Хареба', LinkSrc = '/page/excursion-to-kaheti-winery-hareba.html' WHERE LinkId = 23 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Kakheti. Hareba Wine Factory', LinkSrc = '/en/page/excursion-to-kaheti-winery-hareba.html' WHERE LinkId = 23 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кахетия. Винный завод Хареба', LinkSrc = '/he/page/excursion-to-kaheti-winery-hareba.html' WHERE LinkId = 23 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'Кахетія. Винний завод Хареба', LinkSrc = '/ua/page/excursion-to-kaheti-winery-hareba.html' WHERE LinkId = 23 AND LangID = 4;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'В Армению на 2 дня', LinkSrc = '/page/excursion-to-armenia.html' WHERE LinkId = 24 AND LangID = 1;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'To Armenia for 2 days', LinkSrc = '/en/page/excursion-to-armenia.html' WHERE LinkId = 24 AND LangID = 2;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'В Армению на 2 дня', LinkSrc = '/he/page/excursion-to-armenia.html' WHERE LinkId = 24 AND LangID = 3;
UPDATE gbua_cgdb.LinkBlockLinksData SET LinkTitle = 'До Вірменії на 2 дні', LinkSrc = '/ua/page/excursion-to-armenia.html' WHERE LinkId = 24 AND LangID = 4;
