UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Главная' WHERE LinkID = 1 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Main' WHERE LinkID = 1 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Головна' WHERE LinkID = 1 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Экскурсии' WHERE LinkID = 2 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'One day tours' WHERE LinkID = 2 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Екскурсії' WHERE LinkID = 2 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Многодневные туры' WHERE LinkID = 3 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Multi-day tours' WHERE LinkID = 3 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Багатоденні тури' WHERE LinkID = 3 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Хочу свою программу' WHERE LinkID = 4 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'I want individual programm' WHERE LinkID = 4 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Бажаю свою власну програму' WHERE LinkID = 4 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Свадьба в Грузии' WHERE LinkID = 5 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Wedding in Georgia' WHERE LinkID = 5 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Весілля у Грузії' WHERE LinkID = 5 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Наша команда' WHERE LinkID = 6 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Our team' WHERE LinkID = 6 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Наша команда' WHERE LinkID = 6 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Партнерам' WHERE LinkID = 7 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'For Partners' WHERE LinkID = 7 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Партнерам' WHERE LinkID = 7 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Контакты' WHERE LinkID = 8 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Contacts' WHERE LinkID = 8 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Контакти' WHERE LinkID = 8 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Отзывы' WHERE LinkID = 9 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Reviews' WHERE LinkID = 9 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Відгуки' WHERE LinkID = 9 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Кабинет' WHERE LinkID = 10 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Cabinet' WHERE LinkID = 10 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Кабінет' WHERE LinkID = 10 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/rus.jpg" alt="ru"> Русский' WHERE LinkID = 11 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/rus.jpg" alt="ru"> Русский' WHERE LinkID = 11 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/rus.jpg" alt="ru"> Русский' WHERE LinkID = 11 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/vel.jpg" alt="en"> English' WHERE LinkID = 12 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/vel.jpg" alt="en"> English' WHERE LinkID = 12 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/vel.jpg" alt="en"> English' WHERE LinkID = 12 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/ua.png" alt="ua"> Українська' WHERE LinkID = 14 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/ua.png" alt="ua"> Українська' WHERE LinkID = 14 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = '<img src="/images/flags/ua.png" alt="ua"> Українська' WHERE LinkID = 14 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Отели' WHERE LinkID = 15 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = null WHERE LinkID = 15 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = null WHERE LinkID = 15 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Аренда Авто' WHERE LinkID = 16 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = null WHERE LinkID = 16 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = null WHERE LinkID = 16 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Трансферы' WHERE LinkID = 17 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Transfers' WHERE LinkID = 17 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Трансфери' WHERE LinkID = 17 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Рестораны' WHERE LinkID = 18 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Restaurants' WHERE LinkID = 18 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuLinkData SET Caption = 'Ресторани' WHERE LinkID = 18 AND LangID = 4;
