UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Главная' WHERE OptionID = 1 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Main' WHERE OptionID = 1 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Головна' WHERE OptionID = 1 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Отели' WHERE OptionID = 2 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Hotels' WHERE OptionID = 2 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Готелi' WHERE OptionID = 2 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Туры в Грузию' WHERE OptionID = 3 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Tours to Georgia' WHERE OptionID = 3 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Тури в Грузію' WHERE OptionID = 3 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Аренда Авто' WHERE OptionID = 4 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Rent a Сar' WHERE OptionID = 4 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Оренда Авто' WHERE OptionID = 4 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'О нас' WHERE OptionID = 5 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'About us' WHERE OptionID = 5 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Про нас' WHERE OptionID = 5 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Контакты' WHERE OptionID = 6 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Contacts' WHERE OptionID = 6 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Контакти' WHERE OptionID = 6 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Отзывы' WHERE OptionID = 7 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Reviews' WHERE OptionID = 7 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Відгуки' WHERE OptionID = 7 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Войти' WHERE OptionID = 8 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Signin' WHERE OptionID = 8 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Увійти' WHERE OptionID = 8 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = '<span class="LangButton">&nbsp&nbsp&nbsp&nbsp</span>' WHERE OptionID = 9 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = '<span class="LangButton">&nbsp&nbsp&nbsp&nbsp</span>' WHERE OptionID = 9 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = '<span class="LangButton">&nbsp&nbsp&nbsp&nbsp</span>' WHERE OptionID = 9 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = '<img class="pl-md-2 pr-2" src="/images/call-mob.png" style="height: 1.5em;"> +995 598 00 14 61' WHERE OptionID = 10 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = '<img class="pl-md-2 pr-2" src="/images/call-mob.png" style="height: 1.5em;">+995 598 00 14 61' WHERE OptionID = 10 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = '<img class="pl-md-2 pr-2" src="/images/call-mob.png" style="height: 1.5em;"> +995 598 00 14 61' WHERE OptionID = 10 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Трансферы' WHERE OptionID = 11 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Transfers' WHERE OptionID = 11 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Трансфери' WHERE OptionID = 11 AND LangID = 4;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Рестораны' WHERE OptionID = 12 AND LangID = 1;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Restaurants' WHERE OptionID = 12 AND LangID = 2;
UPDATE gbua_cgdb.MainMenuOptionData SET Name = 'Ресторани' WHERE OptionID = 12 AND LangID = 4;
