UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-in-kazbeg.html', Name = 'Экскурсия в Казбек (Степанцминда) из Тбилиси', TopMenuActive = null WHERE PageID = 1;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-in-tbilisi.html', Name = 'Экскурсия по Тбилиси', TopMenuActive = null WHERE PageID = 2;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-armenia.html', Name = 'Экскурсия в Армению из Тбилиси', TopMenuActive = null WHERE PageID = 3;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-bakuriani.html', Name = 'Экскурсия в Бакуриани из Тбилиси', TopMenuActive = null WHERE PageID = 4;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-borjomi-vardzia.html', Name = 'Экскурсия в Боржоми, Ахалцихе и Вардзию из Тбилиси', TopMenuActive = null WHERE PageID = 5;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-dmanisi-first-europeans.html', Name = 'Экскурсия в Дманиси "Первые европейцы"', TopMenuActive = null WHERE PageID = 6;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-gudauri.html', Name = 'Экскурсия в Гудаури из Тбилиси', TopMenuActive = null WHERE PageID = 7;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-kaheti-winery-hareba.html', Name = 'Экскурсия в Кахетию из Тбилиси (Хареба)', TopMenuActive = null WHERE PageID = 8;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-kaheti-winery-shumi.html', Name = 'Экскурсия в Кахетию из Тбилиси (Шуми)', TopMenuActive = null WHERE PageID = 9;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-monastery-david-gareja.html', Name = 'Экускурсия в монастырь Давид-Гареджа', TopMenuActive = null WHERE PageID = 10;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-mtskheta.html', Name = 'Экскурсия в Мцхету и древние монастыри', TopMenuActive = null WHERE PageID = 11;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-mtskheta-upliscihe-gori.html', Name = 'Экскурсия в Мцхету - Уплисцихе - Гори из Тбилиси', TopMenuActive = null WHERE PageID = 12;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'excursion-to-tbilisi-and-mtskheta.html', Name = 'Экскурсия по Тбилиси и поездка в город Мцхета', TopMenuActive = null WHERE PageID = 13;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'individual-tours.html', Name = 'Индивидуальный тур в Грузию', TopMenuActive = null WHERE PageID = 14;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'rafting-in-georgia.html', Name = 'Рафтинг в Грузии на реке Арагви', TopMenuActive = null WHERE PageID = 15;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-around-georgia-8-days.html', Name = 'Недорогой тур в Грузию на 8 дней', TopMenuActive = null WHERE PageID = 16;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-around-tbilisi-5-days.html', Name = 'Тур в Грузию на 5 дней. Тбилиси', TopMenuActive = null WHERE PageID = 17;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-around-tbilisi-kaheti-5-days.html', Name = 'Тур в Грузию на 5 дней. Тбилиси и Кахетия', TopMenuActive = null WHERE PageID = 18;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-borjomi-vardzia-4-days.html', Name = 'Тур в Грузию на 4 дня: Боржоми, Ахалцихе, Вардзия', TopMenuActive = null WHERE PageID = 19;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-culinary-around-georgia-7-days.html', Name = 'Кулинарный тур в Грузию на 7 дней', TopMenuActive = null WHERE PageID = 20;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-kaheti-3days.html', Name = 'Тур в Грузию на выходные. Кахетия', TopMenuActive = null WHERE PageID = 21;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-kazbeg-3-days.html', Name = 'Тур в Грузию на выходные. Степанцминда (Казбек)', TopMenuActive = null WHERE PageID = 22;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-new-year-5-days.html', Name = 'Новый год в Грузии на 5 дней', TopMenuActive = null WHERE PageID = 23;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-tbilisi-batumi-5-days.html', Name = 'Тур в Грузию на 5 дней. Горы и Море', TopMenuActive = null WHERE PageID = 24;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-tbilisi-batumi-7-days.html', Name = 'Отдых в Грузии на 7 дней. Тбилиси и Батуми', TopMenuActive = null WHERE PageID = 25;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-tbilisi-batumi-10-days.html', Name = 'Отдых в Грузии на 10 дней. От Тбилиси до Батуми', TopMenuActive = null WHERE PageID = 26;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-to-armenia-6-days.html', Name = 'Тур в Грузию и Армению на 6 дней', TopMenuActive = null WHERE PageID = 27;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-to-tbilisi-kazbegi-5-days.html', Name = 'Тур в Грузию на 5 дней: Тбилиси, Мцхета, Казбек, кулинарный мастер-класс', TopMenuActive = null WHERE PageID = 28;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-to-gudauri-5-days.html', Name = 'Зимний тур в Грузию на 6 дней (Гудаури)', TopMenuActive = null WHERE PageID = 29;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'wedding-in-kaheti-3days.html', Name = 'Свадьба в Грузии. Кахетия', TopMenuActive = null WHERE PageID = 30;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'wedding-in-kaheti-3days-all-inclusive.html', Name = 'Свадьба в Грузии. Кахетия. Кварели', TopMenuActive = null WHERE PageID = 31;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'wedding-in-kazbeg-3days.html', Name = 'Свадьба в Грузии. Казбек', TopMenuActive = null WHERE PageID = 32;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'wedding-in-tbilisi-3days.html', Name = 'Свадьба в Грузии. Тбилиси', TopMenuActive = null WHERE PageID = 33;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'about-us.html', Name = 'Наша команда', TopMenuActive = 1 WHERE PageID = 34;
UPDATE gbua_cgdb.Page SET PageTypeID = 5, FileName = 'contacts.html', Name = 'Контакты', TopMenuActive = null WHERE PageID = 35;
UPDATE gbua_cgdb.Page SET PageTypeID = 4, FileName = 'reviews.html', Name = 'Отзывы', TopMenuActive = 1 WHERE PageID = 36;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'to-partners.html', Name = 'Партнерам', TopMenuActive = null WHERE PageID = 37;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'multi-day-tours.html', Name = 'Многодневные туры (Альбом)', TopMenuActive = 1 WHERE PageID = 38;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'wedding-in-georgia.html', Name = 'Свадьба в Грузии (Альбом)', TopMenuActive = 1 WHERE PageID = 39;
UPDATE gbua_cgdb.Page SET PageTypeID = 1, FileName = 'index.html', Name = 'Главная ', TopMenuActive = 1 WHERE PageID = 40;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'excursions.html', Name = 'Экскурсии (Альбом)', TopMenuActive = 1 WHERE PageID = 41;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-tbilisi-kazbegi-borjomi-vardzia-7-days.html', Name = 'Путешествие в Грузию на автомобиле', TopMenuActive = null WHERE PageID = 42;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-tbilisi-kazbegi-5-days.html', Name = 'Тур в Грузию на 5 дней. Тбилиси, Мцхета, Казбек', TopMenuActive = null WHERE PageID = 43;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'tour-tbilisi-4-days.html', Name = 'Тур в Грузию на 4 дня. Тбилиси, Мцхета, кулинарный мастер-класс', TopMenuActive = null WHERE PageID = 44;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'hotels.html', Name = 'Отели (Альбом)', TopMenuActive = 1 WHERE PageID = 45;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'rent-cars.php', Name = 'Аренда авто (Альбом)', TopMenuActive = 1 WHERE PageID = 46;
UPDATE gbua_cgdb.Page SET PageTypeID = 3, FileName = 'guest-house-zemeli.html', Name = 'Отель №3. 3 звезды (вмещает 50 человек)', TopMenuActive = null WHERE PageID = 47;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'transfer.php', Name = 'Трансферы', TopMenuActive = 1 WHERE PageID = 48;
UPDATE gbua_cgdb.Page SET PageTypeID = 2, FileName = 'cafe_redirect.php', Name = 'Рестораны', TopMenuActive = 1 WHERE PageID = 49;
