UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Популярные туры в Грузию', AlbumDescryption = 'Здесь Вы найдете интересные туры в любую точку Грузии, Армении и Азербайджана. Все туры разной продолжительности.
                        Программа подобрана так, чтобы вы успели познакомиться с культурой, традициями, кухней и историей нашей страны.
						 ', AlbumButtonMoreValue = 'Больше туров' WHERE AlbumID = 1 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Popular tours to Georgia', AlbumDescryption = 'Here you will find interesting tours to any place in Georgia, Armenia and Azerbaijan. All tours of different lengths. The program is designed in such a way that you have time to get acquainted with the culture, traditions,                      cuisine and history of our country.', AlbumButtonMoreValue = 'More tours' WHERE AlbumID = 1 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Популярные туры в Грузию', AlbumDescryption = 'Здесь Вы найдете интересные туры в любую точку Грузии, Армении и Азербайджана. Все туры разной продолжительности.
                        Программа подобрана так, чтобы вы успели познакомиться с культурой, традициями, кухней и историей нашей страны. ', AlbumButtonMoreValue = 'Больше туров' WHERE AlbumID = 1 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Популярні тури в Грузію', AlbumDescryption = 'Тут Ви знайдете цікаві тури до будь-якої точки Грузії, Вірменії та Азербайджану. Всі тури різної тривалості. Програма підібрана таким чином, щоб ви встигли познайомитися з культурою, традиціями, кухнею та історією нашої країни.', AlbumButtonMoreValue = 'Більше турів' WHERE AlbumID = 1 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Популярные экскурсии', AlbumDescryption = 'Однодневные экскурсии из Тбилиси в любую точку Грузии, Армении, Азербайджана', AlbumButtonMoreValue = 'Больше экскурсий' WHERE AlbumID = 2 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Popular excursions', AlbumDescryption = 'One-day excursions from Tbilisi to anywhere in Georgia, Armenia, Azerbaijan', AlbumButtonMoreValue = 'More excursions' WHERE AlbumID = 2 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Популярные экскурсии', AlbumDescryption = 'Однодневные экскурсии из Тбилиси в любую точку Грузии, Армении, Азербайджана', AlbumButtonMoreValue = 'Больше экскурсий' WHERE AlbumID = 2 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Популярні екскурсії', AlbumDescryption = 'Одноденні екскурсії з Тбілісі в будь-яку точку Грузії, Вірменії, Азербайджану', AlbumButtonMoreValue = 'Більше екскурсій' WHERE AlbumID = 2 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Экскурсии по Грузии c Cool Georgia Travel', AlbumDescryption = 'Однодневные экскурсии из Тбилиси в любую точку Грузии, Армении, Азербайджана
		
               
           ', AlbumButtonMoreValue = '' WHERE AlbumID = 3 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Excursions to Georgia with company Cool Georgia Travel', AlbumDescryption = 'One-day excursions from Tbilisi to anywhere in Georgia, Armenia, Azerbaijan', AlbumButtonMoreValue = ' ' WHERE AlbumID = 3 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Экскурсии по Грузии c Cool Georgia Travel', AlbumDescryption = 'Однодневные экскурсии из Тбилиси в любую точку Грузии, Армении, Азербайджана', AlbumButtonMoreValue = ' ' WHERE AlbumID = 3 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Екскурсії по Грузії з Cool Georgia Travel', AlbumDescryption = 'Одноденні екскурсії з Тбілісі в будь-яку точку Грузії, Вірменії, Азербайджану', AlbumButtonMoreValue = ' ' WHERE AlbumID = 3 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Экскурсии в Армению из Тбилиси', AlbumDescryption = 'Двухдневные экскурсии в Армению из Тбилиси.Возможность посетить соседнюю с Грузией страну, полюбоваться её достопримечательностями и узнать культуру и традиции ещё одной страны Кавказа ', AlbumButtonMoreValue = ' ' WHERE AlbumID = 4 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Excursions to Armenia from Tbilisi', AlbumDescryption = 'Two-days excursions to Armenia from Tbilisi. The opportunity to visit the neighboring country with Georgia, admire its sights and learn the culture and traditions of another country of the Caucasus', AlbumButtonMoreValue = ' ' WHERE AlbumID = 4 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Экскурсии в Армению из Тбилиси', AlbumDescryption = 'Двухдневные экскурсии в Армению из Тбилиси.Возможность посетить соседнюю с Грузией страну, полюбоваться её достопримечательностями и узнать культуру и традиции ещё одной страны Кавказа ', AlbumButtonMoreValue = ' ' WHERE AlbumID = 4 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Екскурсії до Вірменії з Тбілісі', AlbumDescryption = 'Дводенні екскурсії до Вірменії із Тбілісі. Можливість відвідати сусідню із Грузією країну, помилуватися її визначними пам\'ятками й дізнатися культуру та традиції ще однієї країни Кавказу', AlbumButtonMoreValue = ' ' WHERE AlbumID = 4 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отдых в Грузии на 3 - 4 дня', AlbumDescryption = 'Короткие туры выходного дня. Программа подобрана так, чтобы даже за такое короткое время вы успели почувствовать настоящую Грузию и увидеть её красоту', AlbumButtonMoreValue = '  ' WHERE AlbumID = 5 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Rest in Georgia for 3 - 4 days', AlbumDescryption = 'Short weekend tours. The program is chosen so that even in such a short time you have to feel real Georgia and see its beauty', AlbumButtonMoreValue = ' ' WHERE AlbumID = 5 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отдых в Грузии на 3 - 4 дня', AlbumDescryption = 'Короткие туры выходного дня. Программа подобрана так, чтобы даже за такое короткое время вы успели почувствовать настоящую Грузию и увидеть её красоту', AlbumButtonMoreValue = ' ' WHERE AlbumID = 5 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Відпочинок в Грузії на 3 - 4 дні', AlbumDescryption = 'Короткі тури вихідного дня. 
                    Програма підібрана таким чином, щоб навіть за такий короткий час ви встигли відчути справжню Грузію і побачити її красу.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 5 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отдых в Грузии на 5 - 6 дней', AlbumDescryption = 'Можно ли узнать Грузию меньше, чем за неделю? Давайте это проверим вместе! ', AlbumButtonMoreValue = ' ' WHERE AlbumID = 6 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Rest in Georgia for 5 - 6 days', AlbumDescryption = 'Can you find out more about Georgia in less than a week? Let\'s check it together! ', AlbumButtonMoreValue = ' ' WHERE AlbumID = 6 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отдых в Грузии на 5 - 6 дней', AlbumDescryption = 'Можно ли узнать Грузию меньше, чем за неделю? Давайте это проверим вместе! ', AlbumButtonMoreValue = ' ' WHERE AlbumID = 6 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Відпочинок в Грузії на 5 - 6 днів', AlbumDescryption = 'Чи можна пізнати Грузію менше ніж за тиждень? Давайте перевіримо це разом! ', AlbumButtonMoreValue = ' ' WHERE AlbumID = 6 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отдых в Грузии на 7 дней и более', AlbumDescryption = 'Настало время для grand-туров! Это будет незабываемый отпуск в Грузии! 
                     Мы покажем Вам как живут грузины, что они едят и как это готовят, раскроем тайны рецептов, специй и соусов. 
                     Отвезем Вас в самые красивые места страны. Наш гид расскажет много интересных историй о древних монастырях и городах. Вы поймете, почему мы так любим свою страну и боремся за неё.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 7 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Rest in Georgia for 7 days and more', AlbumDescryption = 'It\'s time for grand-tours! It will be an unforgettable vacation in Georgia! 
                    We will show you how the Georgians live, what they eat and how they cook, we will uncover the secrets of recipes, spices and sauces. 
                    We will take you to the most beautiful places of the country. Our guide will tell you many interesting stories about ancient monasteries and cities. 
                    You will understand why we love our country so much and fighting for it.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 7 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отдых в Грузии на 7 дней и более', AlbumDescryption = 'Настало время для grand-туров! Это будет незабываемый отпуск в Грузии! 
                     Мы покажем Вам как живут грузины, что они едят и как это готовят, раскроем тайны рецептов, специй и соусов. 
                     Отвезем Вас в самые красивые места страны. Наш гид расскажет много интересных историй о древних монастырях и городах. Вы поймете, почему мы так любим свою страну и боремся за неё.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 7 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Відпочинок в Грузії на 7 днів та довше', AlbumDescryption = 'Прийшов час для грандіозних турів! Це буде незабутній відпочинок в Грузії! 
                    Ми покажемо вам, як живуть грузини, що вони їдять і як вони готують, ми розкриємо секрети рецептів, спецій та соусів. 
                    Ми доставимо вас до найкрасивіших місць країни. Наш гід розповідатиме вам багато цікавих історій про стародавні монастирі та міста. 
                    Ви зрозумієте, чому ми так сильно любимо нашу країну і боремося за це.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 7 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Туры по Грузии и Армении (выезд из Тбилиси, или из Еревана)', AlbumDescryption = 'Кавказ большой! Мы хотим познакомить Вас с ещё одной интересной и красивой страной - Армения.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 8 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Tours to Armenia from Tbilisi', AlbumDescryption = 'The Caucasus is big! We want to introduce you with one more interesting and beautiful country - Armenia.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 8 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Туры по Грузии и Армении (выезд из Тбилиси, или из Еревана)', AlbumDescryption = 'Кавказ большой! Мы хотим познакомить Вас с ещё одной интересной и красивой страной - Армения.', AlbumButtonMoreValue = '  ' WHERE AlbumID = 8 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Тури до Вірменії із Тбілісі', AlbumDescryption = 'Кавказ великий! Ми хочемо познайомити Вас із ще однією цікавою і гарною країною - Вірменія.', AlbumButtonMoreValue = ' ' WHERE AlbumID = 8 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Свадьба в Грузии - недорого, но красиво, тонко и изысканно!', AlbumDescryption = 'Свадьба - важное событие в жизни влюбленных людей! Этот день должен запомнится на всю жизнь. Мы поможем Вам в этом!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 9 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Wedding in Georgia - inexpensive, but beautiful, subtle and exquisite!', AlbumDescryption = 'Wedding is an important event in the life of loving people! This day should be remembered for all life. We will help you with this!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 9 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Свадьба в Грузии - недорого, но красиво, тонко и изысканно!', AlbumDescryption = 'Свадьба - важное событие в жизни влюбленных людей! Этот день должен запомнится на всю жизнь. Мы поможем Вам в этом!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 9 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Весілля в Грузії - недорого, але красиво, витончено та вишукано!', AlbumDescryption = 'Весілля - важлива подія в житті люблячих людей! Цей день слід пам\'ятати на все життя. Ми допоможемо вам з цим!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 9 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Свадьба в Грузии с выездной процедурой бракосочетания', AlbumDescryption = 'Для молодоженов, которые хотят шикарную и необычную свадьбу!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 10 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Wedding in Georgia with registration of marriage in a restaurant, hotel or at the nature', AlbumDescryption = 'For the newlyweds who want a chic and unusual wedding!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 10 AND LangID = 2;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Свадьба в Грузии с выездной процедурой бракосочетания', AlbumDescryption = 'Для молодоженов, которые хотят шикарную и необычную свадьбу!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 10 AND LangID = 3;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Весілля в Грузії з оформленням шлюбу в ресторані, готелі або на природі', AlbumDescryption = 'Для молодят, які бажають шикарне та незвичайне весілля!', AlbumButtonMoreValue = ' ' WHERE AlbumID = 10 AND LangID = 4;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отели в городе Тбилиси', AlbumDescryption = 'Здесь вы найдете большой выбор отелей в городе Тбилиси', AlbumButtonMoreValue = ' ' WHERE AlbumID = 11 AND LangID = 1;
UPDATE gbua_cgdb.PageAlbumData SET AlbumCaption = 'Отели в городе Батуми', AlbumDescryption = 'Здесь вы найдете большой выбор отелей в городе Батуми', AlbumButtonMoreValue = ' ' WHERE AlbumID = 12 AND LangID = 1;
