UPDATE gbua_cgdb.Roles SET Name = '(Администрирование) Управление доступом: Группы' WHERE RoleID = 1;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование) Управление доступом: Роли' WHERE RoleID = 2;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование) Управление доступом: Пользоват' WHERE RoleID = 3;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование) Контент: Страницы сайта' WHERE RoleID = 4;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование) Контент: Альбомы' WHERE RoleID = 5;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование) Контент: Карточки' WHERE RoleID = 6;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование): Настройки сайта' WHERE RoleID = 7;
UPDATE gbua_cgdb.Roles SET Name = '(Оператор) Бронирования: Новые ' WHERE RoleID = 8;
UPDATE gbua_cgdb.Roles SET Name = '(Оператор) Бронирования: В работе' WHERE RoleID = 9;
UPDATE gbua_cgdb.Roles SET Name = '(Оператор) Бронирования: Управление отзывами' WHERE RoleID = 10;
UPDATE gbua_cgdb.Roles SET Name = '(Пользователь): Текущие бронирования' WHERE RoleID = 11;
UPDATE gbua_cgdb.Roles SET Name = '(Пользователь): Архив бронирований' WHERE RoleID = 12;
UPDATE gbua_cgdb.Roles SET Name = '(Пользователь): Отзывы' WHERE RoleID = 13;
UPDATE gbua_cgdb.Roles SET Name = '(Пользователь): Профиль' WHERE RoleID = 14;
UPDATE gbua_cgdb.Roles SET Name = '(Пользователь): Выйти' WHERE RoleID = 15;
UPDATE gbua_cgdb.Roles SET Name = '(Администрирование): Генератор сайта' WHERE RoleID = 16;
UPDATE gbua_cgdb.Roles SET Name = '(Пользователь): Заказать услугу' WHERE RoleID = 17;
UPDATE gbua_cgdb.Roles SET Name = '(Оператор) Управление обратными звонками' WHERE RoleID = 18;
UPDATE gbua_cgdb.Roles SET Name = '(Хозяин машины) Список всех машин ' WHERE RoleID = 19;
UPDATE gbua_cgdb.Roles SET Name = '(Хозяин машины) Бронирования: Новые ' WHERE RoleID = 20;
UPDATE gbua_cgdb.Roles SET Name = '(Хозяин машины) Бронирования: В работе ' WHERE RoleID = 21;
