UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Управление доступом' WHERE OptionID = 1 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Access control' WHERE OptionID = 1 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Управління доступом' WHERE OptionID = 1 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Контент' WHERE OptionID = 2 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Content' WHERE OptionID = 2 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Контент' WHERE OptionID = 2 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Настройки сайта' WHERE OptionID = 3 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Site settings' WHERE OptionID = 3 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Налаштунки сайту' WHERE OptionID = 3 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Бронирования' WHERE OptionID = 4 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Bookings' WHERE OptionID = 4 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Бронювання' WHERE OptionID = 4 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Управление отзывами' WHERE OptionID = 5 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Feedback management' WHERE OptionID = 5 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Керування відгуками' WHERE OptionID = 5 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Текущие бронирования' WHERE OptionID = 6 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Current booking' WHERE OptionID = 6 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Поточні бронювання' WHERE OptionID = 6 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Архив бронирований' WHERE OptionID = 7 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Archive of booking' WHERE OptionID = 7 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Архів бронювань' WHERE OptionID = 7 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Мои отзывы' WHERE OptionID = 8 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'My reviews' WHERE OptionID = 8 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Мої відгуки' WHERE OptionID = 8 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Профиль' WHERE OptionID = 9 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Profile' WHERE OptionID = 9 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Профіль' WHERE OptionID = 9 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Выйти' WHERE OptionID = 10 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Logout' WHERE OptionID = 10 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Вийти' WHERE OptionID = 10 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Заявки на обратный звонок' WHERE OptionID = 12 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Callback list' WHERE OptionID = 12 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Замовлення на зворотній дзвінок' WHERE OptionID = 12 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionData SET Name = 'Текущие бронирования авто' WHERE OptionID = 15 AND LangID = 1;
