UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Администрирование' WHERE SectionID = 1 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Administration' WHERE SectionID = 1 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Адміністрування' WHERE SectionID = 1 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Кабинет оператора' WHERE SectionID = 2 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Operator\'s Cabinet' WHERE SectionID = 2 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Кабінет оператора' WHERE SectionID = 2 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Кабинет пользователя' WHERE SectionID = 3 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'User Cabinet' WHERE SectionID = 3 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Особистий кабінет' WHERE SectionID = 3 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionData SET Name = 'Аренда машин' WHERE SectionID = 4 AND LangID = 1;
