UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Группы' WHERE LinkID = 1 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Groups' WHERE LinkID = 1 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Групи' WHERE LinkID = 1 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Роли' WHERE LinkID = 2 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Roles' WHERE LinkID = 2 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Ролі' WHERE LinkID = 2 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Пользователи' WHERE LinkID = 3 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Users' WHERE LinkID = 3 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Користувачі' WHERE LinkID = 3 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Страницы сайта' WHERE LinkID = 4 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Pages of site' WHERE LinkID = 4 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Сторінки сайту' WHERE LinkID = 4 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Альбомы' WHERE LinkID = 5 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Albums' WHERE LinkID = 5 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Альбоми' WHERE LinkID = 5 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Карточки' WHERE LinkID = 6 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Cards' WHERE LinkID = 6 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Картки' WHERE LinkID = 6 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Настройки сайта' WHERE LinkID = 7 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Site settings' WHERE LinkID = 7 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Налаштунки сайту' WHERE LinkID = 7 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Новые' WHERE LinkID = 8 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'New' WHERE LinkID = 8 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Нові' WHERE LinkID = 8 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'В работе' WHERE LinkID = 9 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'In work' WHERE LinkID = 9 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'В роботі' WHERE LinkID = 9 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Управление отзывами' WHERE LinkID = 10 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Reviews management' WHERE LinkID = 10 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Керування відгуками' WHERE LinkID = 10 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Текущие бронирования' WHERE LinkID = 11 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Current booking' WHERE LinkID = 11 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Поточні бронювання' WHERE LinkID = 11 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Архив бронирований' WHERE LinkID = 12 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Arhive of booking' WHERE LinkID = 12 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Архів бронювань' WHERE LinkID = 12 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Мои отзывы' WHERE LinkID = 13 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'My reviews' WHERE LinkID = 13 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Мої відгуки' WHERE LinkID = 13 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Профиль' WHERE LinkID = 14 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Profile' WHERE LinkID = 14 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Профіль' WHERE LinkID = 14 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Выйти' WHERE LinkID = 15 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Logout' WHERE LinkID = 15 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Вийти' WHERE LinkID = 15 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Генератор сайта' WHERE LinkID = 16 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Site generator' WHERE LinkID = 16 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Генератор сайту' WHERE LinkID = 16 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Заявки на обратный звонок' WHERE LinkID = 18 AND LangID = 1;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Callback list' WHERE LinkID = 18 AND LangID = 2;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Замовлення на зворотній дзвінок' WHERE LinkID = 18 AND LangID = 4;
UPDATE gbua_cgdb.SidebarSectionOptionLinkData SET Name = 'Текущие бронирования авто' WHERE LinkID = 19 AND LangID = 1;
